### ISSUE TITLE
create smoke-test for devices/list

### ISSUE THREAD

**Issue by ethanplee14** [seamapi/java#2]
https://hello-seam.slack.com/archives/C01D0J9ACLF/p1689721502439719

**Comment by dsinghvi** [comment]
@ethanplee14 lmk if we (fern team) can be helpful as you add this! 

We are planning to have fern support generating a basic junit test file + github workflows that run the junit tests. That should come in handy as you add unit/integration tests to the sdk.

**Comment by dsinghvi** [comment]
This is now added, closing
